"""
application/ports/repositories.py
=====================================
PORTS SORTANTS — interfaces des dépôts (NOUVEAU SCHEMA avec SchoolYear + Enrollment).
"""
from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Dict, List, Optional

from economat.domain.enrollment.entities import Enrollment
from economat.domain.enrollment.value_objects import EnrollmentId
from economat.domain.payment.entities import Payment
from economat.domain.payment.value_objects import PaymentId
from economat.domain.school.entities import School, SchoolYear
from economat.domain.school.value_objects import ClassId, LevelId, SchoolId, SchoolYearId
from economat.domain.student.entities import Student
from economat.domain.student.value_objects import StudentId


class SchoolRepository(ABC):
    @abstractmethod
    def find_by_id(self, school_id: SchoolId) -> Optional[School]: ...
    @abstractmethod
    def save(self, school: School) -> None: ...
    @abstractmethod
    def find_all(self) -> List[School]: ...


class SchoolYearRepository(ABC):
    @abstractmethod
    def find_by_id(self, year_id: SchoolYearId) -> Optional[SchoolYear]: ...
    @abstractmethod
    def find_by_school(self, school_id: SchoolId) -> List[SchoolYear]: ...
    @abstractmethod
    def find_active(self, school_id: SchoolId) -> Optional[SchoolYear]: ...
    @abstractmethod
    def save(self, year: SchoolYear) -> None: ...
    @abstractmethod
    def next_id(self) -> SchoolYearId: ...


class StudentRepository(ABC):
    @abstractmethod
    def find_by_id(self, student_id: StudentId) -> Optional[Student]: ...
    @abstractmethod
    def find_by_school(self, school_id: SchoolId) -> List[Student]: ...
    @abstractmethod
    def save(self, student: Student) -> None: ...
    @abstractmethod
    def next_id(self) -> StudentId: ...
    @abstractmethod
    def exists(self, student_id: StudentId) -> bool: ...


class EnrollmentRepository(ABC):
    @abstractmethod
    def find_by_id(self, eid: EnrollmentId) -> Optional[Enrollment]: ...
    @abstractmethod
    def find_by_student_and_year(self, student_id: StudentId, year_id: SchoolYearId) -> Optional[Enrollment]: ...
    @abstractmethod
    def find_by_year(self, year_id: SchoolYearId) -> List[Enrollment]: ...
    @abstractmethod
    def find_active_by_year(self, year_id: SchoolYearId) -> List[Enrollment]: ...
    @abstractmethod
    def find_by_class_and_year(self, class_id: ClassId, year_id: SchoolYearId) -> List[Enrollment]: ...
    @abstractmethod
    def save(self, enrollment: Enrollment) -> None: ...
    @abstractmethod
    def next_id(self) -> EnrollmentId: ...


class PaymentRepository(ABC):
    @abstractmethod
    def find_by_id(self, payment_id: PaymentId) -> Optional[Payment]: ...
    @abstractmethod
    def find_by_enrollment(self, enrollment_id: EnrollmentId) -> List[Payment]: ...
    @abstractmethod
    def find_by_school_and_year(self, school_id: SchoolId, year_id: SchoolYearId) -> Dict[str, List[Payment]]: ...
    """Batch anti-N+1 : retourne {enrollment_id_str: [Payment...]}."""
    @abstractmethod
    def save(self, payment: Payment) -> None: ...
    @abstractmethod
    def next_id(self) -> PaymentId: ...
    @abstractmethod
    def last_receipt_number(self, school_id: SchoolId) -> int: ...
