# Generated by Django 5.2.17 on 2026-09-08 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('sender_name', models.CharField(max_length=200, verbose_name="Nom de l'expéditeur")),
                ('receiver_name', models.CharField(max_length=200, verbose_name='Nom du destinataire')),
                ('source_country', models.CharField(db_index=True, max_length=100, verbose_name='Pays source')),
                ('destination_country', models.CharField(db_index=True, max_length=100, verbose_name='Pays de destination')),
                ('agent_name', models.CharField(db_index=True, max_length=200, verbose_name="Nom de l'agent")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant envoyé')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Commission prélevée')),
                ('send_currency', models.CharField(max_length=10, verbose_name="Devise d'envoi")),
                ('payout_currency', models.CharField(max_length=10, verbose_name='Devise de paiement')),
                ('exchange_rate', models.FloatField(verbose_name='Taux de change')),
                ('status', models.CharField(choices=[('completed', 'Complétée'), ('pending', 'En attente'), ('cancelled', 'Annulée'), ('suspended', 'Suspendue')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_status_created'), models.Index(fields=['source_country', 'destination_country'], name='idx_countries')],
            },
        ),
    ]
