# Generated by Django 5.2.17 on 2026-09-09 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('annual_fee', models.PositiveIntegerField()),
                ('payment_mode', models.CharField(choices=[('UNIQUE', 'Paiement unique'), ('MENSUEL', 'Mensualités'), ('TRANCHES', '3 tranches')], default='TRANCHES', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'economat_level',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Sénégal', max_length=100)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('tolerance_days', models.PositiveSmallIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'economat_school',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveSmallIntegerField(default=40)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='economat.levelmodel')),
            ],
            options={
                'db_table': 'economat_class',
                'ordering': ['name'],
                'unique_together': {('level', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SchoolYearModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'En préparation'), ('ACTIVE', 'Active'), ('CLOSED', 'Clôturée')], db_index=True, default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_years', to='economat.schoolmodel')),
            ],
            options={
                'db_table': 'economat_school_year',
                'ordering': ['-label'],
                'unique_together': {('school', 'label')},
            },
        ),
        migrations.AddField(
            model_name='levelmodel',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='economat.schoolyearmodel'),
        ),
        migrations.CreateModel(
            name='EnrollmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('PROMOTED', 'Promu')], db_index=True, default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('klass', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='economat.classmodel')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='economat.levelmodel')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='economat.schoolyearmodel')),
            ],
            options={
                'db_table': 'economat_enrollment',
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='economat.schoolmodel')),
            ],
            options={
                'db_table': 'economat_student',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('payment_date', models.DateField(db_index=True)),
                ('method', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque')], default='ESPECES', max_length=20)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('recorded_by', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('VALID', 'Valide'), ('CANCELLED', 'Annulé')], db_index=True, default='VALID', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='economat.enrollmentmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='economat.studentmodel')),
            ],
            options={
                'db_table': 'economat_payment',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='enrollmentmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='economat.studentmodel'),
        ),
        migrations.CreateModel(
            name='MembershipModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('DIRECTOR', 'Directeur'), ('SECRETARY', 'Secrétaire'), ('ECONOME', 'Économe')], db_index=True, max_length=20)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('login', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='economat.schoolmodel')),
            ],
            options={
                'db_table': 'economat_membership',
                'indexes': [models.Index(fields=['school', 'role', 'is_active'], name='idx_membership_school_role'), models.Index(fields=['user', 'is_active'], name='idx_membership_user_active')],
                'unique_together': {('user', 'school')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='levelmodel',
            unique_together={('school_year', 'name')},
        ),
        migrations.AddIndex(
            model_name='studentmodel',
            index=models.Index(fields=['school'], name='idx_student_school'),
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['enrollment', 'state'], name='idx_payment_enrollment_state'),
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['student', 'payment_date'], name='idx_payment_student_date'),
        ),
        migrations.AddIndex(
            model_name='enrollmentmodel',
            index=models.Index(fields=['school_year', 'status'], name='idx_enrollment_year_status'),
        ),
        migrations.AddIndex(
            model_name='enrollmentmodel',
            index=models.Index(fields=['klass', 'status'], name='idx_enrollment_class_status'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentmodel',
            unique_together={('student', 'school_year')},
        ),
    ]
