# Generated by Django 5.2.17 on 2026-09-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='paid_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='parent_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='parent_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='parent_relation',
            field=models.CharField(blank=True, choices=[('PERE', 'Père'), ('MERE', 'Mère'), ('TUTEUR', 'Tuteur / Tutrice'), ('AUTRE', 'Autre')], default='', max_length=10),
        ),
    ]
