# Generated by Django 5.2.17 on 2026-09-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economat', '0002_add_parent_contact_and_paid_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='client_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID généré côté client (idempotence offline).', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='installment_label',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='matricule',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='receipt_number',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
