# Generated by Django 5.2.17 on 2026-09-11 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economat', '0003_offline_matricule_idempotence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineCredentialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifier', models.CharField(max_length=256)),
                ('offline_salt', models.CharField(max_length=64)),
                ('iterations', models.PositiveIntegerField(default=200000)),
                ('expires_at', models.DateTimeField()),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offline_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'economat_offline_credential',
            },
        ),
    ]
