# Generated by Django 5.2.17 on 2026-09-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("economat", "0004_offline_auth_credential"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmodel",
            name="mobile_operator",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
