# Generated by Django 5.2.17 on 2026-09-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("economat", "0005_paymentmodel_mobile_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmodel",
            name="mobile_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
