# Generated by Django 5.2.17 on 2026-09-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("economat", "0006_paymentmodel_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmodel",
            name="channel",
            field=models.CharField(
                choices=[("GUICHET", "Guichet"), ("PORTAIL_PARENT", "Portail parent")],
                default="GUICHET",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="gateway_transaction_ref",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="state",
            field=models.CharField(
                choices=[
                    ("VALID", "Valide"),
                    ("PENDING", "En attente"),
                    ("CANCELLED", "Annulé"),
                ],
                db_index=True,
                default="VALID",
                max_length=20,
            ),
        ),
    ]
