# Generated by Django 5.2.17 on 2026-09-15 09:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economat', '0008_countrymodel_school_country_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SchoolRegistrationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField(blank=True, db_index=True, help_text='UUID généré côté client (idempotence anti-doublon).', null=True, unique=True)),
                ('school_name', models.CharField(max_length=200, verbose_name="Nom de l'école")),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('manager_first_name', models.CharField(max_length=100, verbose_name='Prénom du gérant')),
                ('manager_last_name', models.CharField(max_length=100, verbose_name='Nom du gérant')),
                ('manager_email', models.EmailField(max_length=254, verbose_name='Email du gérant')),
                ('manager_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone du gérant')),
                ('payment_methods', models.JSONField(blank=True, default=list, help_text='Liste JSON, ex. ["ESPECES", "MOBILE_MONEY"]', verbose_name="Moyens d'encaissement")),
                ('mobile_operator', models.CharField(blank=True, default='', max_length=60, verbose_name='Opérateur Mobile Money')),
                ('mobile_number', models.CharField(blank=True, default='', max_length=30, verbose_name='Numéro Mobile Money')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACTIVATED', 'Activée'), ('REJECTED', 'Rejetée')], db_index=True, default='PENDING', max_length=12, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, default='', help_text='Commentaires de validation (visibles seulement en admin).', verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Soumise le')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Activée le')),
                ('activated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_registration', to=settings.AUTH_USER_MODEL, verbose_name='Compte créé')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='economat.countrymodel', verbose_name='Pays')),
                ('created_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='economat.schoolmodel', verbose_name='École créée')),
            ],
            options={
                'verbose_name': "Demande d'inscription",
                'verbose_name_plural': "Demandes d'inscription",
                'db_table': 'economat_school_registration',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_registration_status_date'), models.Index(fields=['manager_email'], name='idx_registration_email')],
            },
        ),
    ]
