# Generated by Django 5.2.17 on 2026-09-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("economat", "0009_schoolregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="countrymodel",
            name="dial_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Ex. "+221"',
                max_length=6,
                verbose_name="Indicatif téléphonique",
            ),
        ),
    ]
