# Generated by Django 5.2.17 on 2026-09-15 14:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economat', '0011_backfill_dial_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialCustomerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country_name', models.CharField(blank=True, default='', help_text="Nom du pays saisi librement par l'internaute.", max_length=100, verbose_name='Pays')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enregistré le')),
            ],
            options={
                'verbose_name': 'Client potentiel',
                'verbose_name_plural': 'Clients potentiels',
                'db_table': 'economat_potential_customer',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='idx_potential_email'), models.Index(fields=['created_at'], name='idx_potential_created_at')],
            },
        ),
    ]
