# Generated by Django 5.2.17 on 2026-09-16 11:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economat', '0012_potential_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelmodel',
            name='nb_months',
            field=models.PositiveSmallIntegerField(default=10, help_text='Nombre de mensualités (pertinent uniquement si mode = Mensualités).', verbose_name='Nombre de mois'),
        ),
        migrations.CreateModel(
            name='FeeItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Libellé')),
                ('category', models.CharField(choices=[('SCOLARITE', 'Scolarité'), ('CANTINE', 'Cantine'), ('SORTIES', 'Sorties scolaires'), ('SPORT', 'Activités sportives'), ('FOURNITURES', 'Fournitures scolaires'), ('AUTRE', 'Autre')], db_index=True, max_length=20, verbose_name='Catégorie')),
                ('amount', models.PositiveIntegerField(default=0, help_text='Montant total attendu. Pour les lignes système, synchronisé avec le tarif du niveau.', verbose_name='Montant (FCFA)')),
                ('scope_type', models.CharField(choices=[('LEVEL', 'Niveau entier'), ('CLASS', 'Classe précise')], default='LEVEL', max_length=10)),
                ('payment_mode', models.CharField(choices=[('UNIQUE', 'Paiement unique'), ('MENSUEL', 'Mensualités'), ('TRANCHES', '3 tranches')], default='UNIQUE', max_length=20)),
                ('nb_months', models.PositiveSmallIntegerField(default=10, help_text='Nombre de mensualités (pertinent uniquement si mode = Mensualités).', verbose_name='Nombre de mois')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('is_system', models.BooleanField(db_index=True, default=False, help_text='Si coché, ligne générée automatiquement (scolarité). Ne pas modifier.', verbose_name='Ligne système')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('klass', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_items', to='economat.classmodel', verbose_name='Classe')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_items', to='economat.levelmodel', verbose_name='Niveau')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_items', to='economat.schoolyearmodel')),
            ],
            options={
                'verbose_name': 'Ligne de frais',
                'verbose_name_plural': 'Lignes de frais',
                'db_table': 'economat_fee_item',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='fee_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_for_fee', to='economat.feeitemmodel', verbose_name='Poste de frais'),
        ),
        migrations.AddIndex(
            model_name='feeitemmodel',
            index=models.Index(fields=['school_year', 'is_active'], name='idx_fee_item_year_active'),
        ),
        migrations.AddIndex(
            model_name='feeitemmodel',
            index=models.Index(fields=['school_year', 'category'], name='idx_fee_item_year_category'),
        ),
        migrations.AddIndex(
            model_name='feeitemmodel',
            index=models.Index(fields=['level', 'is_system'], name='idx_fee_item_level_system'),
        ),
    ]
