# Generated by Django 5.2.17 on 2026-09-16 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economat', '0014_backfill_fee_items_scolarite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeitemmodel',
            name='klass',
        ),
        migrations.AddField(
            model_name='feeitemmodel',
            name='class_ids',
            field=models.JSONField(blank=True, default=list, help_text='Liste JSON de class_ids. Vide si scope_type=ALL.', verbose_name='Classes ciblées'),
        ),
        migrations.AlterField(
            model_name='feeitemmodel',
            name='category',
            field=models.CharField(choices=[('SCOLARITE', 'Scolarité'), ('CANTINE', 'Cantine'), ('TRANSPORT', 'Transport scolaire'), ('SORTIES', 'Sorties scolaires'), ('SPORT', 'Activités sportives'), ('FOURNITURES', 'Fournitures scolaires'), ('AUTRE', 'Autre')], db_index=True, max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='feeitemmodel',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_items', to='economat.levelmodel', verbose_name='Niveau (scolarité système)'),
        ),
        migrations.AlterField(
            model_name='feeitemmodel',
            name='scope_type',
            field=models.CharField(choices=[('ALL', 'Toutes les classes'), ('CLASSES', 'Classes sélectionnées')], default='ALL', max_length=10, verbose_name='Portée'),
        ),
    ]
