# Generated by Django 5.2.17 on 2026-09-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economat', '0016_backfill_fee_scope_class_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeitemmodel',
            name='class_amounts',
            field=models.JSONField(blank=True, default=dict, help_text='Surcharges optionnelles, ex. {"<uuid-CP>": 10000, "<uuid-CM>": 15000}. Si absent pour une classe, le montant par défaut (amount) s\'applique.', verbose_name='Montants par classe'),
        ),
    ]
